/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import static cnpm.Connecting.Connect;
import java.sql.ResultSet;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.processing.Messager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author USER
 */
public class AddServices extends javax.swing.JFrame {

    public String id;
    public AddServices() {
    initComponents();
      
            //Ban đầu cho các lb ẩn
        lbErrorService.setVisible(false);
        lbErrorServiceEmpty.setVisible(false);
        lbErrorPriceEmpty.setVisible(false);
        lbErrorServiceExisting.setVisible(false);
        lbErrorPriceValid.setVisible(false);
        //Set nut update an
        btUpdate.setVisible(false);
        lbUpdate.setVisible(false);
        btDelete.setVisible(false);
        lbDelete.setVisible(false);
        this.setSize(400,290);
   this.getContentPane().setBackground(new Color(209, 209, 224));
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBackground = new javax.swing.JPanel();
        panelRegister = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        txtServiceName = new javax.swing.JTextField();
        lbUpdate = new javax.swing.JLabel();
        lbAdding = new javax.swing.JLabel();
        btAdding = new javax.swing.JButton();
        lbDelete = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        txtMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        btUpdate = new javax.swing.JButton();
        lbErrorService = new javax.swing.JLabel();
        lbErrorServiceEmpty = new javax.swing.JLabel();
        lbErrorPriceValid = new javax.swing.JLabel();
        lbErrorPriceEmpty = new javax.swing.JLabel();
        lbErrorServiceExisting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setOpacity(0.95F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegister.setBackground(new java.awt.Color(51, 51, 51));
        panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Services", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(255, 255, 102))); // NOI18N
        panelRegister.setPreferredSize(new java.awt.Dimension(250, 530));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(51, 51, 51));
        txtPrice.setText("PRICE*");
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        panelRegister.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 50));

        txtServiceName.setBackground(new java.awt.Color(255, 255, 255));
        txtServiceName.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtServiceName.setForeground(new java.awt.Color(51, 51, 51));
        txtServiceName.setText("SERVICES NAME*");
        txtServiceName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtServiceName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtServiceNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtServiceNameFocusLost(evt);
            }
        });
        panelRegister.add(txtServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 50));

        lbUpdate.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbUpdate.setForeground(new java.awt.Color(255, 255, 102));
        lbUpdate.setText("UPDATE");
        panelRegister.add(lbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 120, 30));

        lbAdding.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbAdding.setForeground(new java.awt.Color(255, 255, 102));
        lbAdding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdding.setText("ADD");
        panelRegister.add(lbAdding, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 30));

        btAdding.setBackground(new java.awt.Color(102, 102, 102));
        btAdding.setForeground(new java.awt.Color(255, 255, 0));
        btAdding.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btAdding.setBorder(null);
        btAdding.setBorderPainted(false);
        btAdding.setContentAreaFilled(false);
        panelRegister.add(btAdding, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, 70));

        lbDelete.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbDelete.setForeground(new java.awt.Color(255, 255, 102));
        lbDelete.setText("LOCK UP");
        panelRegister.add(lbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, 30));

        btDelete.setBackground(new java.awt.Color(102, 102, 102));
        btDelete.setForeground(new java.awt.Color(255, 255, 0));
        btDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btDelete.setBorder(null);
        btDelete.setBorderPainted(false);
        btDelete.setContentAreaFilled(false);
        panelRegister.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 70));

        txtMinimize.setBackground(new java.awt.Color(51, 51, 51));
        txtMinimize.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtMinimize.setForeground(new java.awt.Color(255, 255, 102));
        txtMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinimize.setText("-");
        txtMinimize.setOpaque(true);
        txtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseExited(evt);
            }
        });
        panelRegister.add(txtMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 20));

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 102));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setOpaque(true);
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        panelRegister.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 20));

        btUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btUpdate.setForeground(new java.awt.Color(255, 255, 0));
        btUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btUpdate.setBorder(null);
        btUpdate.setBorderPainted(false);
        btUpdate.setContentAreaFilled(false);
        panelRegister.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 70));

        panelBackground.add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        lbErrorService.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
        lbErrorService.setForeground(new java.awt.Color(255, 92, 51));
        lbErrorService.setText("Servicename's invalid");
        getContentPane().add(lbErrorService, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 210, 40));

        lbErrorServiceEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
        lbErrorServiceEmpty.setForeground(new java.awt.Color(255, 92, 51));
        lbErrorServiceEmpty.setText("Servicename's empty");
        lbErrorServiceEmpty.setToolTipText("");
        getContentPane().add(lbErrorServiceEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, -1));

        lbErrorPriceValid.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
        lbErrorPriceValid.setForeground(new java.awt.Color(255, 92, 51));
        lbErrorPriceValid.setText("Price's invalid");
        lbErrorPriceValid.setToolTipText("");
        getContentPane().add(lbErrorPriceValid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, -1));

        lbErrorPriceEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
        lbErrorPriceEmpty.setForeground(new java.awt.Color(255, 92, 51));
        lbErrorPriceEmpty.setText("Price's empty");
        lbErrorPriceEmpty.setToolTipText("");
        getContentPane().add(lbErrorPriceEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, -1));

        lbErrorServiceExisting.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
        lbErrorServiceExisting.setForeground(new java.awt.Color(255, 92, 51));
        lbErrorServiceExisting.setText("Servicename's existing");
        getContentPane().add(lbErrorServiceExisting, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(new Color(200, 0,0));
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseExited
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtMinimizeMouseExited

    private void txtMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseEntered
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(200, 0,0));
    }//GEN-LAST:event_txtMinimizeMouseEntered

    private void txtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_txtMinimizeMouseClicked
   
    private void txtServiceNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceNameFocusLost
        // TODO add your handling code here:
        if(txtServiceName.getText().trim().toUpperCase().equals(""))
        {
            txtServiceName.setFont(new Font("Dubai Light", Font.ITALIC, 16));
            txtServiceName.setForeground(new Color(51,51,51));
            txtServiceName.setText("SERVICES NAME*");
        }
    }//GEN-LAST:event_txtServiceNameFocusLost

    private void txtServiceNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceNameFocusGained
        // TODO add your handling code here:
        if(txtServiceName.getText().trim().toUpperCase().equals("SERVICES NAME*"))
        {
            txtServiceName.setFont(new Font("Dialog", Font.BOLD, 16));
            txtServiceName.setForeground(new Color(10, 15, 15));
            txtServiceName.setText("");
        }
    }//GEN-LAST:event_txtServiceNameFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        // TODO add your handling code here:
        if(txtPrice.getText().trim().toUpperCase().equals(""))
        {
            txtPrice.setFont(new Font("Dubai Light", Font.ITALIC, 16));
            txtPrice.setForeground(new Color(51,51,51));
            txtPrice.setText("PRICE*");
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        // TODO add your handling code here:
        if(txtPrice.getText().trim().toUpperCase().equals("PRICE*"))
        {
            txtPrice.setFont(new Font("Dialog", Font.BOLD, 16));
            txtPrice.setForeground(new Color(10, 15, 15));
            txtPrice.setText("");
        }
    }//GEN-LAST:event_txtPriceFocusGained
                 
    /**
     * @param args the command line arguments
     */
    private void createServices(String serviceName,String price)
    {
        try {
            Connection connect=Connect();
            String sql1=" insert into DichVu values (?,?)";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            pr1.setString(1, serviceName);
            pr1.setString(2, price);
            pr1.executeUpdate();
            pr1.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdding;
    public javax.swing.JButton btDelete;
    public javax.swing.JButton btUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel lbAdding;
    public javax.swing.JLabel lbDelete;
    public javax.swing.JLabel lbErrorPriceEmpty;
    public javax.swing.JLabel lbErrorPriceValid;
    public javax.swing.JLabel lbErrorService;
    public javax.swing.JLabel lbErrorServiceEmpty;
    public javax.swing.JLabel lbErrorServiceExisting;
    public javax.swing.JLabel lbUpdate;
    private javax.swing.JPanel panelBackground;
    public javax.swing.JPanel panelRegister;
    public javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtMinimize;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtServiceName;
    // End of variables declaration//GEN-END:variables
}
