/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {
      String staffName;
      String userName;
      String position;
      String idStaff;
      int xx,xy;

    public String getIdStaff() {
        return idStaff;
    }

    public void setIdStaff(String idStaff) {
        this.idStaff = idStaff;
    }
     updateAccessoriesAndBrand ab=new updateAccessoriesAndBrand();
     updateAccessoriesPanel ap=new updateAccessoriesPanel();
     updateBrandCart bc=new updateBrandCart();
    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
      

    public String getStaffName() {
        return staffName;
    }

    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }


     
    boolean display=true;

    public boolean isDisplay() {
        return display;
    }

    public void setDisplay(boolean display) {
        this.display = display;
    }
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        //ẨN LB ĐẺ HIỆN TỪNG CÁI
        panelDetailAccesories.removeAll();
        panelDetailGuestCar.removeAll();
        panelDetailInforGuest.removeAll();
        panelDetailInvoice.removeAll();
        panelDetailSevice.removeAll();
        panelDetailStaff.removeAll();
        lbTextSevice.setVisible(false);
        lbTextStaff.setVisible(false);
        panelDetailAccesories.setVisible(false);
        panelDetailSevice.setVisible(false);
        panelDetailStaff.setVisible(false);
        panelDetailInforGuest.setVisible(false);
        panelDetailGuestCar.setVisible(false);
        panelDetailInvoice.setVisible(false);
        
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        lbTextInforDetailInvoice.setVisible(false);
        lbTextInforGuestCar.setVisible(false);
        lbTextInforGuest.setVisible(false);
        lbTextAccessories.setVisible(false);
        lbStockStaff.setVisible(false);
        lbAccountant.setVisible(false);
        lbManager.setVisible(false);
        lbLogout.setBackground(new Color(204,204,204,150));
        lbLogout.setVisible(false);
        this.setSize(1200, 600);
        this.setBackground(new Color(50,50,50,150));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        lbLogout = new javax.swing.JLabel();
        panelDetailInvoice = new javax.swing.JPanel();
        lbSettingInvoice = new javax.swing.JLabel();
        panelDetailGuestCar = new javax.swing.JPanel();
        panelDetailInforGuest = new javax.swing.JPanel();
        lbSettingGuest = new javax.swing.JLabel();
        panelDetailAccesories = new javax.swing.JPanel();
        lbSettingAccess = new javax.swing.JLabel();
        panelDetailSevice = new javax.swing.JPanel();
        lbSettingService = new javax.swing.JLabel();
        panelDetailStaff = new javax.swing.JPanel();
        lbSettingStaff = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbTextInforDetailInvoice = new javax.swing.JLabel();
        lbTextInforGuest = new javax.swing.JLabel();
        lbTextSevice = new javax.swing.JLabel();
        lbTextStaff = new javax.swing.JLabel();
        lbTextAccessories = new javax.swing.JLabel();
        lbTextInforGuestCar = new javax.swing.JLabel();
        lbStaffIcon = new javax.swing.JLabel();
        lbStaffIcon1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbStock = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        lbService = new javax.swing.JLabel();
        lbSell = new javax.swing.JLabel();
        lbIconUserFemale = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbIconUserMale = new javax.swing.JLabel();
        lbManager = new javax.swing.JLabel();
        lbStockStaff = new javax.swing.JLabel();
        lbAccountant = new javax.swing.JLabel();
        lbInforGuest = new javax.swing.JLabel();
        lbInforGuestCar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 100, 100));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogout.setBackground(new java.awt.Color(255, 255, 255));
        lbLogout.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lbLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_logout_rounded_left_16.png")); // NOI18N
        lbLogout.setText("Log out");
        lbLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbLogout.setOpaque(true);
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLogoutMouseExited(evt);
            }
        });
        getContentPane().add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 20));

        panelDetailInvoice.setBackground(new java.awt.Color(255, 255, 255));

        lbSettingInvoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\364_64.png")); // NOI18N

        javax.swing.GroupLayout panelDetailInvoiceLayout = new javax.swing.GroupLayout(panelDetailInvoice);
        panelDetailInvoice.setLayout(panelDetailInvoiceLayout);
        panelDetailInvoiceLayout.setHorizontalGroup(
            panelDetailInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailInvoiceLayout.createSequentialGroup()
                .addComponent(lbSettingInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1040, Short.MAX_VALUE))
        );
        panelDetailInvoiceLayout.setVerticalGroup(
            panelDetailInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailInvoiceLayout.createSequentialGroup()
                .addComponent(lbSettingInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(596, Short.MAX_VALUE))
        );

        getContentPane().add(panelDetailInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1110, 650));

        panelDetailGuestCar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelDetailGuestCarLayout = new javax.swing.GroupLayout(panelDetailGuestCar);
        panelDetailGuestCar.setLayout(panelDetailGuestCarLayout);
        panelDetailGuestCarLayout.setHorizontalGroup(
            panelDetailGuestCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        panelDetailGuestCarLayout.setVerticalGroup(
            panelDetailGuestCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(panelDetailGuestCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1110, 650));

        panelDetailInforGuest.setBackground(new java.awt.Color(255, 255, 255));

        lbSettingGuest.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\364_64.png")); // NOI18N

        javax.swing.GroupLayout panelDetailInforGuestLayout = new javax.swing.GroupLayout(panelDetailInforGuest);
        panelDetailInforGuest.setLayout(panelDetailInforGuestLayout);
        panelDetailInforGuestLayout.setHorizontalGroup(
            panelDetailInforGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailInforGuestLayout.createSequentialGroup()
                .addComponent(lbSettingGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1040, Short.MAX_VALUE))
        );
        panelDetailInforGuestLayout.setVerticalGroup(
            panelDetailInforGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailInforGuestLayout.createSequentialGroup()
                .addComponent(lbSettingGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 596, Short.MAX_VALUE))
        );

        getContentPane().add(panelDetailInforGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1110, 650));

        panelDetailAccesories.setBackground(new java.awt.Color(255, 255, 255));

        lbSettingAccess.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\364_64.png")); // NOI18N

        javax.swing.GroupLayout panelDetailAccesoriesLayout = new javax.swing.GroupLayout(panelDetailAccesories);
        panelDetailAccesories.setLayout(panelDetailAccesoriesLayout);
        panelDetailAccesoriesLayout.setHorizontalGroup(
            panelDetailAccesoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSettingAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelDetailAccesoriesLayout.setVerticalGroup(
            panelDetailAccesoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSettingAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(panelDetailAccesories, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1110, 650));

        panelDetailSevice.setBackground(new java.awt.Color(255, 255, 255));

        lbSettingService.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\364_64.png")); // NOI18N

        javax.swing.GroupLayout panelDetailSeviceLayout = new javax.swing.GroupLayout(panelDetailSevice);
        panelDetailSevice.setLayout(panelDetailSeviceLayout);
        panelDetailSeviceLayout.setHorizontalGroup(
            panelDetailSeviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailSeviceLayout.createSequentialGroup()
                .addComponent(lbSettingService, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1040, Short.MAX_VALUE))
        );
        panelDetailSeviceLayout.setVerticalGroup(
            panelDetailSeviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailSeviceLayout.createSequentialGroup()
                .addComponent(lbSettingService, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 596, Short.MAX_VALUE))
        );

        getContentPane().add(panelDetailSevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1110, 650));

        panelDetailStaff.setBackground(new java.awt.Color(255, 255, 255));

        lbSettingStaff.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\364_64.png")); // NOI18N

        javax.swing.GroupLayout panelDetailStaffLayout = new javax.swing.GroupLayout(panelDetailStaff);
        panelDetailStaff.setLayout(panelDetailStaffLayout);
        panelDetailStaffLayout.setHorizontalGroup(
            panelDetailStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailStaffLayout.createSequentialGroup()
                .addComponent(lbSettingStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1040, Short.MAX_VALUE))
        );
        panelDetailStaffLayout.setVerticalGroup(
            panelDetailStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailStaffLayout.createSequentialGroup()
                .addComponent(lbSettingStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 616, Short.MAX_VALUE))
        );

        getContentPane().add(panelDetailStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 1110, 670));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 1110, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTextInforDetailInvoice.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextInforDetailInvoice.setForeground(new java.awt.Color(51, 0, 0));
        lbTextInforDetailInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextInforDetailInvoice.setText("MANAGING INVOICE");
        jPanel1.add(lbTextInforDetailInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 420, 50));

        lbTextInforGuest.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextInforGuest.setForeground(new java.awt.Color(51, 0, 0));
        lbTextInforGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextInforGuest.setText("MANAGING GUEST");
        jPanel1.add(lbTextInforGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 420, 50));

        lbTextSevice.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextSevice.setForeground(new java.awt.Color(51, 0, 0));
        lbTextSevice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextSevice.setText("SERVICES CAR LIST");
        jPanel1.add(lbTextSevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 445, 50));

        lbTextStaff.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextStaff.setForeground(new java.awt.Color(51, 0, 0));
        lbTextStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextStaff.setText("STAFF LIST");
        jPanel1.add(lbTextStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 365, 50));

        lbTextAccessories.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextAccessories.setForeground(new java.awt.Color(51, 0, 0));
        lbTextAccessories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextAccessories.setText("MANAGING STOCK");
        jPanel1.add(lbTextAccessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 445, 50));

        lbTextInforGuestCar.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTextInforGuestCar.setForeground(new java.awt.Color(51, 0, 0));
        lbTextInforGuestCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextInforGuestCar.setText("MANAGING GUEST'S CAR");
        jPanel1.add(lbTextInforGuestCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 490, 50));

        lbStaffIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\1_64.png")); // NOI18N
        jPanel1.add(lbStaffIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 100, 60));

        lbStaffIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\1_64.png")); // NOI18N
        jPanel1.add(lbStaffIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 0, 90, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\4_64.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1110, 50));

        lbStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStock.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_used_product_48.png")); // NOI18N
        lbStock.setToolTipText("Manging Stock");
        lbStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbStockMouseExited(evt);
            }
        });
        getContentPane().add(lbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 60));

        lbStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStaff.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\Hot_48.png")); // NOI18N
        lbStaff.setToolTipText("Edit Staff's Information");
        lbStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbStaffMouseExited(evt);
            }
        });
        getContentPane().add(lbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, 60));

        lbService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbService.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_car_service_48.png")); // NOI18N
        lbService.setToolTipText("Services Car");
        lbService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbServiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbServiceMouseExited(evt);
            }
        });
        getContentPane().add(lbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 120, 70));

        lbSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSell.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_bill_48.png")); // NOI18N
        lbSell.setToolTipText("Selling");
        lbSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSellMouseExited(evt);
            }
        });
        getContentPane().add(lbSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 120, 60));

        lbIconUserFemale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconUserFemale.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_female_profile_64.png")); // NOI18N
        lbIconUserFemale.setToolTipText("Edit Staff's Information");
        lbIconUserFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconUserFemaleMouseClicked(evt);
            }
        });
        getContentPane().add(lbIconUserFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 70));

        lbUser.setBackground(new java.awt.Color(255, 255, 255));
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 40));

        lbIconUserMale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconUserMale.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_circled_user_male_skin_type_4_64.png")); // NOI18N
        lbIconUserMale.setToolTipText("Edit Staff's Information");
        lbIconUserMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconUserMaleMouseClicked(evt);
            }
        });
        getContentPane().add(lbIconUserMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 70));

        lbManager.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_crown_32.png")); // NOI18N
        getContentPane().add(lbManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        lbStockStaff.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_staff_sergeant_ssg_32.png")); // NOI18N
        getContentPane().add(lbStockStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        lbAccountant.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_ring_details_32.png")); // NOI18N
        getContentPane().add(lbAccountant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        lbInforGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInforGuest.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\InforGuest_48.png")); // NOI18N
        lbInforGuest.setToolTipText("Information Guest");
        lbInforGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInforGuestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbInforGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbInforGuestMouseExited(evt);
            }
        });
        getContentPane().add(lbInforGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 60));

        lbInforGuestCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInforGuestCar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\Carguest_48.png")); // NOI18N
        lbInforGuestCar.setToolTipText("Guest's Car");
        lbInforGuestCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInforGuestCarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbInforGuestCarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbInforGuestCarMouseExited(evt);
            }
        });
        getContentPane().add(lbInforGuestCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStaffMouseEntered
        // TODO add your handling code here:
        lbStaff.setOpaque(true);
        lbStaff.setBackground(Color.white);
    }//GEN-LAST:event_lbStaffMouseEntered

    private void lbStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStaffMouseExited
        // TODO add your handling code here:
        lbStaff.setOpaque(false);
        lbStaff.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbStaffMouseExited

    private void lbStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStockMouseEntered
        // TODO add your handling code here:
        lbStock.setOpaque(true);
        lbStock.setBackground(Color.white);
    }//GEN-LAST:event_lbStockMouseEntered

    private void lbStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStockMouseExited
        // TODO add your handling code here:
        lbStock.setOpaque(false);
        lbStock.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbStockMouseExited

    private void lbServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbServiceMouseEntered
        // TODO add your handling code here:
        lbService.setOpaque(true);
        lbService.setBackground(Color.white);
    }//GEN-LAST:event_lbServiceMouseEntered

    private void lbServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbServiceMouseExited
        // TODO add your handling code here:
        lbService.setOpaque(false);
        lbService.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbServiceMouseExited

    private void lbSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseEntered
        // TODO add your handling code here:
        lbSell.setOpaque(true);
        lbSell.setBackground(Color.white);
    }//GEN-LAST:event_lbSellMouseEntered

    private void lbSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseExited
        // TODO add your handling code here:
        lbSell.setOpaque(false);
        lbSell.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbSellMouseExited

    private void lbStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStaffMouseClicked
        // TODO add your handling code here:
        this.setSize(1200, 600);
        panelDetailStaff.removeAll();
        lbTextStaff.setVisible(true);
        lbTextSevice.setVisible(false);
        lbTextAccessories.setVisible(false);
        lbTextInforGuest.setVisible(false);
         lbTextInforGuestCar.setVisible(false);
        lbTextInforDetailInvoice.setVisible(false);      
        
        lbStaffIcon.setVisible(true);
        lbStaffIcon1.setVisible(true);
        panelDetailInvoice.setVisible(false);
        panelDetailGuestCar.setVisible(false);
        panelDetailInforGuest.setVisible(false);
        //panelDetailBrandCart.setVisible(false);
        panelDetailSevice.setVisible(false);
         panelDetailAccesories.setVisible(false);
        panelDetailStaff.setVisible(true);
        upDateStaffPanel a=new upDateStaffPanel();
       a.setUserNameStaff(getUserName());
        panelDetailStaff.setLayout(null);
        a.setBounds(0, 0,1200, 550);
        panelDetailStaff.add(a);
        a.setVisible(true);
        
    }//GEN-LAST:event_lbStaffMouseClicked

    private void lbIconUserFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconUserFemaleMouseClicked
        // TODO add your handling code here:
        lbLogout.setVisible(isDisplay());
           if(isDisplay()==true)
           {
               setDisplay(false);
           }
           else
           {
               setDisplay(true);
           }
    }//GEN-LAST:event_lbIconUserFemaleMouseClicked

    private void lbIconUserMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconUserMaleMouseClicked
        // TODO add your handling code here:
        lbLogout.setVisible(isDisplay());
           if(isDisplay()==true)
           {
               setDisplay(false);
           }
           else
           {
               setDisplay(true);
           }
    }//GEN-LAST:event_lbIconUserMaleMouseClicked

    private void lbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseEntered
        // TODO add your handling code here:
        lbLogout.setBackground(Color.gray);
    }//GEN-LAST:event_lbLogoutMouseEntered

    private void lbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseExited
        // TODO add your handling code here:
        lbLogout.setBackground(new Color(204,204,204,150));
    }//GEN-LAST:event_lbLogoutMouseExited

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        // TODO add your handling code here:
        dispose();
        Login a=new Login();
        a.setVisible(true);
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbServiceMouseClicked
        // TODO add your handling code here:
       
        panelDetailSevice.removeAll();
         lbTextSevice.setVisible(true);
        lbTextStaff.setVisible(false);
        lbTextAccessories.setVisible(false);
       // panelDetailBrandCart.setVisible(false);
         lbTextInforGuest.setVisible(false);
         lbTextInforGuestCar.setVisible(false);
         lbTextInforDetailInvoice.setVisible(false);      
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        
        panelDetailInvoice.setVisible(false);
         
        panelDetailGuestCar.setVisible(false);   
        panelDetailInforGuest.setVisible(false);
        panelDetailStaff.setVisible(false);
        panelDetailAccesories.setVisible(false);
        panelDetailSevice.setVisible(true);
        updateService b=new updateService();
        panelDetailSevice.setLayout(null);
       

        b.setBounds(0, 0,1200, 570);
        panelDetailSevice.add(b);
        b.setVisible(true);
         this.setSize(1200, 600);
        
    }//GEN-LAST:event_lbServiceMouseClicked

    private void lbStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStockMouseClicked
        // TODO add your handling code here:
        this.setSize(1200, 600);
        lbStaff.setBackground(Color.white);
        panelDetailAccesories.removeAll();
        lbTextSevice.setVisible(false);
        lbTextStaff.setVisible(false);
        lbTextAccessories.setVisible(true);
        ab.setVisible(true);
        bc.setVisible(false);
        ap.setVisible(false);
        lbTextInforGuest.setVisible(false);
        lbTextInforGuestCar.setVisible(false);
        lbTextInforDetailInvoice.setVisible(false);      
        
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        panelDetailInvoice.setVisible(false);
        panelDetailGuestCar.setVisible(false);
        panelDetailInforGuest.setVisible(false);
        panelDetailSevice.setVisible(false);
        panelDetailAccesories.setVisible(true);
        panelDetailStaff.setVisible(false);
        //panelDetailBrandCart.setVisible(false);
        ab=new updateAccessoriesAndBrand();
        ab.setBounds(100, 50,1000, 550);
        panelDetailAccesories.add(ab);
        ab.setVisible(true);
        
        ab.lbTextManage.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)
            {
                
                ab.setVisible(false);
                bc.getInforBrand();
                panelDetailAccesories.setLayout(null);
                bc.setBounds(25, 0,1000, 600);
                panelDetailAccesories.add(bc);
                bc.setVisible(true);
                setSize(1000, 600);
                
            }
        });
        ab.lbTextManage1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)
            {
                
                if(getPosition().equals("Thu ngân"))
                {
                    ap.btAdd.setVisible(false);
                }
                ab.setVisible(false);
                ap.getInforAccessories();
                panelDetailAccesories.add(ap);
                ap.setBounds(0, 0,1000, 600);
                ap.setPosition(getPosition());
                ap.setVisible(true);
                setSize(1000, 600);
                
                
            }
        });
    }//GEN-LAST:event_lbStockMouseClicked

    private void lbInforGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestMouseExited
        // TODO add your handling code here:
         lbInforGuest.setOpaque(false);
        lbInforGuest.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbInforGuestMouseExited

    private void lbInforGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestMouseEntered
        // TODO add your handling code here:
                lbInforGuest.setOpaque(true);
        lbInforGuest.setBackground(Color.white);
        
    }//GEN-LAST:event_lbInforGuestMouseEntered

    private void lbInforGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestMouseClicked
        // TODO add your handling code here:
        panelDetailInforGuest.removeAll();
        lbTextSevice.setVisible(false);
        lbTextStaff.setVisible(false);
        lbTextAccessories.setVisible(false);
        lbTextInforGuest.setVisible(true);
        lbTextInforGuestCar.setVisible(false);
         lbTextInforDetailInvoice.setVisible(false);      
        
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        panelDetailInvoice.setVisible(false);  
        panelDetailGuestCar.setVisible(false);
        panelDetailStaff.setVisible(false);
        panelDetailAccesories.setVisible(false);
        panelDetailSevice.setVisible(false);
        panelDetailInforGuest.setVisible(true);
        updatePanelGuest b=new updatePanelGuest();
        panelDetailInforGuest.setLayout(null);
        panelDetailInforGuest.setSize(1000, 550);
        b.setBounds(70, 0,1100, 550);
        panelDetailInforGuest.add(b);
        b.setStaffName(getStaffName());
        b.setVisible(true);

         this.setSize(1200, 600);
        
        
        
    }//GEN-LAST:event_lbInforGuestMouseClicked

    private void lbInforGuestCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestCarMouseClicked
        // TODO add your handling code here:
        panelDetailGuestCar.removeAll();
        lbTextSevice.setVisible(false);
        lbTextStaff.setVisible(false);
        lbTextAccessories.setVisible(false);
        lbTextInforGuest.setVisible(false);
        lbTextInforGuestCar.setVisible(true);
        lbTextInforDetailInvoice.setVisible(false);      
        
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        panelDetailInvoice.setVisible(false);   
        panelDetailGuestCar.setVisible(true);
        panelDetailStaff.setVisible(false);
        panelDetailAccesories.setVisible(false);
        panelDetailSevice.setVisible(false);
        panelDetailInforGuest.setVisible(false);
        updateGuestCar b=new updateGuestCar();
        panelDetailGuestCar.setLayout(null);
        System.out.println(getIdStaff());
        b.setIdstaff(getIdStaff());
        b.setBounds(0, 0,1200, 700);
        panelDetailGuestCar.setSize(1200, 600);
        panelDetailGuestCar.add(b);
        b.setVisible(true);
        upDateStaffPanel sp=new upDateStaffPanel();
        if(sp.getPosittionFromID(getIdStaff()).equals("Quản kho"))
        {
            b.btMakeAInvoice.setVisible(false);
            b.btAdd.setVisible(false);
        }
        this.setSize(1200, 600);
           
    }//GEN-LAST:event_lbInforGuestCarMouseClicked

    private void lbInforGuestCarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestCarMouseEntered
        // TODO add your handling code here:
          lbInforGuestCar.setOpaque(true);
        lbInforGuestCar.setBackground(Color.white);
    }//GEN-LAST:event_lbInforGuestCarMouseEntered

    private void lbInforGuestCarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGuestCarMouseExited
        // TODO add your handling code here:
         lbInforGuestCar.setOpaque(false);
        lbInforGuestCar.setBackground(new Color(0,0,0,100));
    }//GEN-LAST:event_lbInforGuestCarMouseExited

    private void lbSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseClicked
        // TODO add your handling code here:

        panelDetailInvoice.removeAll();
        lbTextSevice.setVisible(false);
        lbTextStaff.setVisible(false);
        lbTextAccessories.setVisible(false);
        lbTextInforGuest.setVisible(false);
        lbTextInforGuestCar.setVisible(false);
        lbTextInforDetailInvoice.setVisible(true);      
        lbStaffIcon.setVisible(false);
        lbStaffIcon1.setVisible(false);
        
        panelDetailInvoice.setVisible(true);   
        panelDetailGuestCar.setVisible(false);
        panelDetailStaff.setVisible(false);
        panelDetailAccesories.setVisible(false);
        panelDetailSevice.setVisible(false);
        panelDetailInforGuest.setVisible(false);
        updateDetailInvoice b=new updateDetailInvoice();
        panelDetailInvoice.setLayout(null);
        b.setBounds(0, 0,1100, 550);
        panelDetailInvoice.add(b);
        b.setVisible(true);
        this.setSize(1200, 600);
        
    }//GEN-LAST:event_lbSellMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        this.setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         this.setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbAccountant;
    public javax.swing.JLabel lbIconUserFemale;
    public javax.swing.JLabel lbIconUserMale;
    public javax.swing.JLabel lbInforGuest;
    public javax.swing.JLabel lbInforGuestCar;
    private javax.swing.JLabel lbLogout;
    public javax.swing.JLabel lbManager;
    public javax.swing.JLabel lbSell;
    public javax.swing.JLabel lbService;
    private javax.swing.JLabel lbSettingAccess;
    private javax.swing.JLabel lbSettingGuest;
    private javax.swing.JLabel lbSettingInvoice;
    private javax.swing.JLabel lbSettingService;
    private javax.swing.JLabel lbSettingStaff;
    public javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbStaffIcon;
    private javax.swing.JLabel lbStaffIcon1;
    public javax.swing.JLabel lbStock;
    public javax.swing.JLabel lbStockStaff;
    private javax.swing.JLabel lbTextAccessories;
    private javax.swing.JLabel lbTextInforDetailInvoice;
    private javax.swing.JLabel lbTextInforGuest;
    private javax.swing.JLabel lbTextInforGuestCar;
    private javax.swing.JLabel lbTextSevice;
    private javax.swing.JLabel lbTextStaff;
    public javax.swing.JLabel lbUser;
    private javax.swing.JPanel panelDetailAccesories;
    private javax.swing.JPanel panelDetailGuestCar;
    private javax.swing.JPanel panelDetailInforGuest;
    private javax.swing.JPanel panelDetailInvoice;
    private javax.swing.JPanel panelDetailSevice;
    private javax.swing.JPanel panelDetailStaff;
    // End of variables declaration//GEN-END:variables
}
