/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import static cnpm.Connecting.Connect;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class updateAccessoriesPanel extends javax.swing.JPanel {
String brandId;
String brandName;
String getEverything;
String position;

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }
boolean check;

    public boolean isCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }

    public String getGetEverything() {
        return getEverything;
    }

    public void setGetEverything(String getEverything) {
        this.getEverything = getEverything;
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public String getBrandId() {
        return brandId;
    }

    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }
    /**
     * Creates new form updateAccessoriesPanel
     */
    public updateAccessoriesPanel() {
        initComponents();
//        Image img=new ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\Wheel.png").getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
//        lbIcon.setIcon(new ImageIcon(img));
                tbAccessories.getTableHeader().setFont(new Font("DialogInput",Font.BOLD,14));
        tbAccessories.getTableHeader().setOpaque(false);
        tbAccessories.getTableHeader().setBackground(new Color(204, 204, 255));
        getInforAccessories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAccessories = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lbIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\search_30px.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 41, 40));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 403));

        tbAccessories.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tbAccessories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ACCESSORY ID", "ACCESSORIES NAME", "BRAND", "QUANTITY", "UNIT PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAccessories.setRowHeight(24);
        tbAccessories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAccessoriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAccessories);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 666, 321));

        btAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_plus_min1111111us_32.png")); // NOI18N
        btAdd.setText("ADD ACCESSORIES");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 126, -1, 46));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 130, 240, 41));

        lbIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\kisspng-car-spare-part-royalty-free-stock-photography-auto-parts-5ac39839f366e2.153324481522767929997.png")); // NOI18N
        add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 270, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void tbAccessoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAccessoriesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)tbAccessories.getModel();
        AddAccessories a=new AddAccessories();
        updateBrandCart bc=new updateBrandCart();
        int index=tbAccessories.getSelectedRow();
        if (evt.getClickCount()==2)
        {
            a.setVisible(true);

                        //Dinh Dang lai Form dang ki
                        a.btAdd.setVisible(false);
                        a.lbAdd.setVisible(false);
                        a.btUpdate.setVisible(true);
                        a.lbUpdate.setVisible(true);
                        a.btDelete.setVisible(true);
                        a.lbDelete.setVisible(true);
                        a.panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Updating", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(255, 255, 102)));
         if(getPosition().equals("Thu ngân"))
        {
            
            a.btDelete.setVisible(false);
            a.btUpdate.setVisible(false);
            a.lbDelete.setVisible(false);
            a.lbUpdate.setVisible(false);
            a.txtAccessoriesName.setEditable(false);
            a.txtQuantity.setEditable(false);
        }
                        //SET GIÁ TRỊ CHO CÁC TRƯỜNG
                        //ID
                        String id=String.valueOf(tbAccessories.getValueAt(index, 0));
            
                        //NAME Accessories
                        a.txtAccessoriesName.setText(String.valueOf(tbAccessories.getValueAt(index, 1)));
                        String checkAccessName=String.valueOf(tbAccessories.getValueAt(index, 1));
            
                        //Combox Brand
                       String brandid=String.valueOf(tbAccessories.getValueAt(index, 2));
                       String checkBrandName=String.valueOf(tbAccessories.getValueAt(index, 2));
//                       getBrandName(brandid);
//                       a.cbBrandName.getEditor().setItem(getBrandName());
                        
                        
                        
                        //QUANTITY
                        a.txtQuantity.setText(String.valueOf(tbAccessories.getValueAt(index, 3)));
                        a.txtQuantity.setFont(new Font("Dialog",Font.BOLD,16));
                        a.txtQuantity.setForeground(Color.black);

                        
                         //PRICE
                        a.txtPrice.setText(String.valueOf(tbAccessories.getValueAt(index, 4)));
                        a.txtPrice.setFont(new Font("Dialog",Font.BOLD,16));
                        a.txtPrice.setForeground(Color.black);
                   
                        //BrandName;
                        getBrandID(String.valueOf(tbAccessories.getValueAt(index, 2)));
                        a.cbBrandName.setSelectedItem(brandid);
                        a.btUpdate.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent arg0) {
  
                                        int countfull=0;
                                        int countvalid=0;

                                        //ACCESSORIES'S NAME 
                                        boolean checkEmptyAccessoriesName=true;
                                        boolean checkAccessories=true;
                                         boolean checkAccessExisting=true;
                                        String name=a.txtAccessoriesName.getText().trim().replaceAll("\\s+", " ").toUpperCase();
                                        if(name.equals("ACCESSORIES NAME*") || name.isEmpty())
                                        {
                                            countfull++;
                                            checkEmptyAccessoriesName=false;
                                        }
                                        else if (name.length()>30)
                                        {
                                            countvalid++;
                                            checkAccessories=false;
                                        }

                                        //QUANTITY
                                        boolean checkEmptyQuantity=true;
                                        boolean checkQuantity=true;
                                      
                                        String quantity=a.txtQuantity.getText();
                                        if(quantity.equals("QUANTITY*") || quantity.isEmpty())
                                        {

                                            countfull++;
                                            checkEmptyQuantity=false;
                                        }
                                        else 
                                        {
                                            for (int i=0;i<quantity.length();i++)
                                            {

                                                if (quantity.charAt(i)>=48 && quantity.charAt(i)<=57)
                                                {
                                                    checkQuantity=true;
                                                }
                                                else
                                                {
                                                    checkQuantity=false;
                                                    countvalid++;
                                                    break;
                                                }
                                            }
                                        }


                                       String brand=String.valueOf(a.cbBrandName.getEditor().getItem());
                                       getBrandID(brand);

                                        //PRICE
                                        String price=a.txtPrice.getText();
                                        boolean checkEmptyPrice=true;
                                        boolean checkPrice=true;
                                        if(price.equals("PRICE*") || price.isEmpty())
                                        {

                                            countfull++;
                                            checkEmptyPrice=false;
                                        }
                                        else 
                                        {
                                            for (int i=0;i<price.length();i++)
                                            {

                                                if (price.charAt(i)>=48 && price.charAt(i)<=57)
                                                {
                                                    checkPrice=true;
                                                }
                                                else
                                                {
                                                    checkPrice=false;
                                                    countvalid++;
                                                    break;
                                                }
                                            }
                                        }
                                     if(checkAccessName.equals(name) && checkBrandName.equals(brand) )
                                     {
                                         checkAccessExisting=true;
                                     }
                                        
                                     else
                                        {
                                            if (checkNameAndBrandAcessExisting(name, brand)==true)
                                            {
                                                countvalid++;
                                                checkAccessExisting=false;
                                            }
                                        }
                                    
                                    if(countfull!=0 || countvalid!=0)
                                    {
                                         a.setSize(600,330);
                                        //NAME ACCESSORIES
                                        if(checkEmptyAccessoriesName==false)
                                        {

                                            a.lbErrorAccessNameEmpty.setVisible(true);
                                            a.lbErrorAccessName.setVisible(false);
                                        }
                                        else if(checkAccessories==false)
                                        {
                                            a.lbErrorAccessNameEmpty.setVisible(false);
                                            a.lbErrorAccessName.setVisible(true);
                                        }
                                        else
                                        {
                                            a.lbErrorAccessNameEmpty.setVisible(false);
                                            a.lbErrorAccessName.setVisible(false);
                                        }

                                        //QUANTITY
                                        if(checkEmptyQuantity==false)
                                        {
                                            a.lbErrorQuantityEmpty.setVisible(true);
                                            a.lBErrorQuantity.setVisible(false);
                                        }
                                        else if(checkQuantity==false)
                                        {
                                            a.lBErrorQuantity.setVisible(true);
                                            a.lbErrorQuantityEmpty.setVisible(false);
                                        }
                                        else
                                        {
                                            a.lBErrorQuantity.setVisible(false);
                                            a.lbErrorQuantityEmpty.setVisible(false);
                                        }

                                        //PRICE
                                        if(checkEmptyPrice==false)
                                        {
                                            a.lbErrorPriceEmpty.setVisible(true);
                                            a.lbErrorPrice.setVisible(false);
                                        }
                                        else if(checkPrice==false)
                                        {
                                            a.lbErrorPrice.setVisible(true);
                                            a.lbErrorPriceEmpty.setVisible(false);
                                        }
                                        else
                                        {
                                            a.lbErrorPrice.setVisible(false);
                                            a.lbErrorPriceEmpty.setVisible(false);
                                        }
                                                            //EXISTING
                                    if(checkAccessExisting==false)
                                    {
                                        a.lbErrorAccessExisting.setVisible(true);
                                    }
                                    else
                                    {
                                        a.lbErrorAccessExisting.setVisible(false);
                                    }

                                    }
                                     else   if(countvalid==0 && countfull==0)
                                        {
                                            a.setSize(400,330);
                                            updateAccessories(name, getBrandId(), quantity, price, id);
                                            JOptionPane.showMessageDialog(null,"SUCCESSFUL","BINGO!",JOptionPane.PLAIN_MESSAGE,new ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_good_quality_32.png"));
                                             a.dispose();
                                            getInforAccessories();

                                        }
                                    }
                            });
        
                  
                a.btDelete.addActionListener(new ActionListener()
                        {
                                public void actionPerformed(ActionEvent e)
                                {
                                    if(checkAccessInDetailAccess(id)==true)
                                    {
                                        JOptionPane.showMessageDialog(null, "THIS ACCESSORY'S USED! YOU CAN'T LOCK UP", "FAILED",JOptionPane.ERROR_MESSAGE);
                                     

                                    }
                                    else
                                    {
                                        updateStateAccessories("1", id);
                                        JOptionPane.showMessageDialog(null,"SUCCESSFUL","BINGO!",JOptionPane.PLAIN_MESSAGE,new ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_good_quality_32.png"));
                                        a.dispose();
                                        getInforAccessories();
                                    }
                                     
                                    }
                            });
    }

    }//GEN-LAST:event_tbAccessoriesMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        AddAccessories rm=new AddAccessories();
        rm.setVisible(true);
       
        rm.btAdd.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent t)
                {
                    int countfull=0;
                    int countvalid=0;

                    //ACCESSORIES'S NAME 
                    boolean checkEmptyAccessoriesName=true;
                    boolean checkAccessories=true;
                    boolean checkAccessExisting=true;
                    String name=rm.txtAccessoriesName.getText().trim().replaceAll("\\s+", " ").toUpperCase();
                    if(name.equals("ACCESSORIES NAME*") || name.isEmpty())
                    {
                        countfull++;
                        checkEmptyAccessoriesName=false;
                    }
                    else if (name.length()>30)
                    {
                        countvalid++;
                        checkAccessories=false;
                    }

                    //USER
                    boolean checkEmptyQuantity=true;
                    boolean checkQuantity=true;
                    String quantity=rm.txtQuantity.getText();
                    if(quantity.equals("QUANTITY*") || quantity.isEmpty())
                    {

                        countfull++;
                        checkEmptyQuantity=false;
                    }
                    else 
                    {
                        for (int i=0;i<quantity.length();i++)
                        {
                           
                            if (quantity.charAt(i)>=48 && quantity.charAt(i)<=57)
                            {
                                checkQuantity=true;
                            }
                            else
                            {
                                checkQuantity=false;
                                countvalid++;
                                break;
                            }
                        }
                    }

                   
                   String brand=String.valueOf(rm.cbBrandName.getEditor().getItem());
                    if(brand.isEmpty() )
                   {
                       brand="AUDI";
                   }
                   String brandid=new String();
                   getBrandID(brand);
                   //System.out.print(getBrandId());

                    //PHONE NUMBER
                    String price=rm.txtPrice.getText();
                    boolean checkEmptyPrice=true;
                    boolean checkPrice=true;
                    if(price.equals("PRICE*") || price.isEmpty())
                    {

                        countfull++;
                        checkEmptyPrice=false;
                    }
                    else 
                    {
                        for (int i=0;i<price.length();i++)
                        {
                           
                            if (price.charAt(i)>=48 && price.charAt(i)<=57)
                            {
                                checkPrice=true;
                            }
                            else
                            {
                                checkPrice=false;
                                countvalid++;
                                break;
                            }
                        }
                    }
                   if(checkNameAndBrandAcessExisting(name, brand)==true && GetStateAccessory(name, getBrandId()).equals("0"))
                   {
                       countvalid++;
                       checkAccessExisting=false;
                   }
                    //NAME ACCESSORIES
                    if(checkEmptyAccessoriesName==false)
                    {

                        rm.lbErrorAccessNameEmpty.setVisible(true);
                        rm.lbErrorAccessName.setVisible(false);
                    }
                    else if(checkAccessories==false)
                    {
                        rm.lbErrorAccessNameEmpty.setVisible(false);
                        rm.lbErrorAccessName.setVisible(true);
                    }
                    else
                    {
                        rm.lbErrorAccessNameEmpty.setVisible(false);
                        rm.lbErrorAccessName.setVisible(false);
                    }

                    //QUANTITY
                    if(checkEmptyQuantity==false)
                    {
                        rm.lbErrorQuantityEmpty.setVisible(true);
                        rm.lBErrorQuantity.setVisible(false);
                    }
                    else if(checkQuantity==false)
                    {
                        rm.lBErrorQuantity.setVisible(true);
                        rm.lbErrorQuantityEmpty.setVisible(false);
                    }
                    else
                    {
                        rm.lBErrorQuantity.setVisible(false);
                        rm.lbErrorQuantityEmpty.setVisible(false);
                    }
                    
                    //PRICE
                    if(checkEmptyPrice==false)
                    {
                        rm.lbErrorPriceEmpty.setVisible(true);
                        rm.lbErrorPrice.setVisible(false);
                    }
                    else if(checkPrice==false)
                    {
                        rm.lbErrorPrice.setVisible(true);
                        rm.lbErrorPriceEmpty.setVisible(false);
                    }
                    else
                    {
                        rm.lbErrorPrice.setVisible(false);
                        rm.lbErrorPriceEmpty.setVisible(false);
                    }
                    //EXISTING
                    if(checkAccessExisting==false)
                    {
                        rm.lbErrorAccessExisting.setVisible(true);
                    }
                    else
                    {
                        rm.lbErrorAccessExisting.setVisible(false);
                    }

                    if(countvalid==0 && countfull==0)
                    {
                        rm.setSize(400,330);
                        if(checkNameAndBrandAcessExisting(name, brand)==true)
                        {
                            updateStateAccessories("0", GetIDAccessory(name, getBrandId()));
                            updatePriceAndQuantityAccessories(GetIDAccessory(name, getBrandId()), price, quantity);
                             JOptionPane.showMessageDialog(null,"SUCCESSFUL","BINGO!",JOptionPane.PLAIN_MESSAGE,new ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_good_quality_32.png"));
                            getInforAccessories();
                        }
                        else
                        {
                        createAccessories(name, getBrandId(), quantity, price,"0");
                        JOptionPane.showMessageDialog(null,"SUCCESSFUL","BINGO!",JOptionPane.PLAIN_MESSAGE,new ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\Image\\icons8_good_quality_32.png"));
                        getInforAccessories();
                        }
                        //SET VE BAN DAU CHO CAC COMPONENT
                        //NAME ACCESSORIES
                        rm.txtAccessoriesName.setFont(new Font("Dubai Light", Font.ITALIC, 16));
                        rm.txtAccessoriesName.setForeground(new Color(51,51,51));
                        rm.txtAccessoriesName.setText("ACCESSORIES NAME*");

                        //QUANTITY
                        rm.txtQuantity.setFont(new Font("Dubai Light", Font.ITALIC, 16));
                        rm.txtQuantity.setForeground(new Color(51,51,51));
                        rm.txtQuantity.setText("QUANTITY*");

                        //
                        rm.txtPrice.setFont(new Font("Dubai Light", Font.ITALIC, 16));
                        rm.txtPrice.setForeground(new Color(51,51,51));
                        rm.txtPrice.setText("PRICE*");
                    }
                    else
                    {
                        rm.setSize(600,330);
                    }
                }
            });

    }//GEN-LAST:event_btAddActionPerformed
public void  filterData(String query)
{
    DefaultTableModel dtm= (DefaultTableModel)tbAccessories.getModel();
    TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(dtm);
    tbAccessories.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query));
}
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String query=jTextField1.getText().toUpperCase();
        filterData(query);
    }//GEN-LAST:event_jTextField1KeyReleased
 public void getInforAccessories()
    {
        updateBrandCart bc=new updateBrandCart();
        DefaultTableModel dtm=(DefaultTableModel)tbAccessories.getModel();
        dtm.setRowCount(0);
        tbAccessories.setModel(dtm);
        tbAccessories.getColumnModel().getColumn(0).setPreferredWidth(70);
        tbAccessories.getColumnModel().getColumn(1).setPreferredWidth(120);
        tbAccessories.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbAccessories.getColumnModel().getColumn(3).setPreferredWidth(30);
        tbAccessories.getColumnModel().getColumn(4).setPreferredWidth(30);
        tbAccessories.setRowHeight(30);
        tbAccessories.setAutoResizeMode(tbAccessories.AUTO_RESIZE_LAST_COLUMN);
        Connection c=Connecting.Connect();
        String sql="Select * from LinhKien";
        Vector v;
        try {
            PreparedStatement pr=c.prepareStatement(sql);
            ResultSet rs=pr.executeQuery();
            while(rs.next())
            {
                if(rs.getString(6).equals("0"))
                {
                v=new Vector();
                v.add(rs.getString(1)); 
                v.add(rs.getString(2));
                v.add(bc.changeBrandIDIntoBrandName(rs.getString(3)));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                dtm.addRow(v);
                }
            }
            tbAccessories.setModel(dtm);
            rs.close();
            pr.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(upDateStaffPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   public void deleteAccessories(String id)
     {
         Connection c=Connect();
         String sql="delete from LinhKien where MALK=?";
         PreparedStatement pr;
    try {
         pr = c.prepareStatement(sql);
         pr.setString(1, id);
            pr.executeUpdate();
            pr.close();
            c.close();
    } catch (SQLException ex) {
        System.out.print("HELLO");
    }
     }   
   public boolean checkNameAndBrandAcessExisting(String accessoryName, String brandName)
   {
       setCheck(false);
         try {
             updateBrandCart bc=new updateBrandCart();
            Connection connect=Connect();
            String sql1=" select TENLK,MAHANG From LinhKien ";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs=pr1.executeQuery();
            while(rs.next())
            {
                    if(rs.getString(1).equals(accessoryName) && bc.changeBrandIDIntoBrandName(rs.getString(2)).equals(brandName))
                            {
                                setCheck(true);
                                break;
                            }
            }
            pr1.close();
            rs.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
       return isCheck();
   }
      public boolean checkNameAndBrandAcessExistingWithUpdate(String accessoryName, String brandid)
   {
       setCheck(false);
         try {
             updateBrandCart bc=new updateBrandCart();
            Connection connect=Connect();
            String sql1="Select MAHANG,TENLK from LinhKien where NOT MAHANG='"+brandid+"' AND TENLK NOT LIKE N'%"+accessoryName+"%'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs=pr1.executeQuery();
            while(rs.next())
            {
                    if(rs.getString(1).equals(accessoryName) && rs.getString(2).equals(brandid))
                     {
                                setCheck(true);
                                break;
                     }
            }
            pr1.close();
            rs.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
       return isCheck();
   }
      
   private void createAccessories(String accessoriesName,String brandId,String quantity,String price,String status)
    {
        try {
            Connection connect=Connect();
            String sql1=" insert into LinhKien values (?,?,?,?,?)";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            pr1.setString(1, accessoriesName);
            pr1.setString(2, brandId);
            pr1.setString(3, quantity);
            pr1.setString(4, price);
            pr1.setString(5, status);
            pr1.executeUpdate();
            pr1.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private void getBrandID(String brandName)
   {
        try {
            Connection connect=Connect();
            String sql1=" select MAHANG From HangXe where TENHANG='"+brandName+"'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs=pr1.executeQuery();
            while(rs.next())
            {
            setBrandId(rs.getString(1));
            }
            pr1.close();
            rs.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
      private void getBrandName(String brandID)
   {
        try {
            Connection connect=Connect();
            String sql1=" select TENHANG From HangXe where MAHANG='"+brandID+"'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs=pr1.executeQuery();
            while(rs.next())
            {
            System.out.println(rs.getString(1));
            setBrandName(rs.getString(1));
            }
            pr1.close();
            rs.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
         public String getAccessName(String AccessID)
   {
        try {
            Connection connect=Connect();
            String sql1=" select TENLK From LinhKien where MALK='"+AccessID+"'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs=pr1.executeQuery();
            while(rs.next())
            {
           
                setGetEverything(rs.getString(1));
            }
            pr1.close();
            rs.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
        return getGetEverything();
   }
         
         
         
         public boolean checkAccessInDetailAccess(String accessID)
         {
           setCheck(false);
            try {
            Connection connect=Connect();
            String sql1="Select MALK from ChiTietLinhKien";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs1=pr1.executeQuery();
            while(rs1.next())
            {
                    if(rs1.getString(1).equals(accessID))
                     {
                                setCheck(true);
                                break;
                     }
            }
            pr1.close();
            rs1.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
       return isCheck();
             
         }
         
         
         
        
    private void updateAccessories(String accessoriesName,String brandID,String quantity,String price, String accessoriesID)
  {
   Connection c=Connect();
   String sql="update LinhKien set TENLK=?,MAHANG=?,SOLUONG=?,DONGIA=? where MALK=' "+accessoriesID+"'";
        try {
            PreparedStatement pr=c.prepareStatement(sql);
            pr.setString(1, accessoriesName);
            pr.setString(2, brandID);
            pr.setString(3, quantity);
            pr.setString(4, price);
            pr.executeUpdate();
            pr.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 }
  private void updateStateAccessories(String status, String accessoriesID)
  {
   Connection c=Connect();
   String sql="update LinhKien set TRANGTHAI=? where MALK=' "+accessoriesID+"'";
        try {
            PreparedStatement pr=c.prepareStatement(sql);
            pr.setString(1, status);
            pr.executeUpdate();
            pr.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 }
    private void updatePriceAndQuantityAccessories(String accessID,String price,String quantity)
  {
   Connection c=Connect();
   String sql="update LinhKien set SOLUONG=?, DONGIA=? where MALK='"+accessID+"'";
        try {
            PreparedStatement pr=c.prepareStatement(sql);
            pr.setString(1, quantity);
            pr.setString(2, price);
            pr.executeUpdate();
            pr.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 }
  public String GetIDAccessory(String nameAccess,String idBrand)
  {
            try {
            Connection connect=Connect();
            String sql1="Select MALK from LinhKien where MAHANG='"+idBrand+"' and TENLK like N'%"+nameAccess+"%'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs1=pr1.executeQuery();
            while(rs1.next())
            {
                    setGetEverything(rs1.getString(1));
            }
            pr1.close();
            rs1.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
       return getGetEverything();
             
  }
    public String GetStateAccessory(String nameAccess,String idBrand)
  {
            try {
            Connection connect=Connect();
            String sql1="Select TRANGTHAI from LinhKien where MAHANG='"+idBrand+"' and TENLK like N'%"+nameAccess+"%'";
            PreparedStatement pr1=connect.prepareStatement(sql1);
            ResultSet rs1=pr1.executeQuery();
            while(rs1.next())
            {
                    setGetEverything(rs1.getString(1));
            }
            pr1.close();
            rs1.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
        }
       return getGetEverything();
             
  }
    public static void main(String[] args) {
        JFrame a=new JFrame();
        updateAccessoriesPanel b=new updateAccessoriesPanel();
        a.add(b);
        a.pack();
        a.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdd;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JTable tbAccessories;
    // End of variables declaration//GEN-END:variables
}
