/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import static cnpm.Connecting.Connect;
import java.sql.ResultSet;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.processing.Messager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;


/**
 *
 * @author USER
 */
public class RegisterMember extends javax.swing.JFrame {
    /**
     * Creates new form RegisterMember
     */
    upDateStaffPanel t;
    public String id;
    public RegisterMember() {
    initComponents();
    radioNam.setSelected(true);
    cbPosittion.setSelectedItem("Quản lí");
    cbDate.setEnabled(true);
    cbDate.setLocked(false);
    cbDate.setCalendarBackground(Color.gray);
    Calendar cal = Calendar.getInstance();
    cal.clear();
    cal.set(Calendar.YEAR, 1999);
    cal.set(Calendar.MONTH, 01);
    cal.set(Calendar.DATE, 01);
    cbDate.setSelectedDate(cal);
            //Ban đầu cho các lb ẩn
        lbErrorMail.setVisible(false);
        lbErrorPhone.setVisible(false);
        lbErrorUserName.setVisible(false);
        lbErrorUserNameExisting.setVisible(false);
        lbErrorPass.setVisible(false);
        lbErrorAddressEmpty.setVisible(false);
        lbErrorMailEmpty.setVisible(false);
        lbErrorNameEmpty.setVisible(false);
        lbErrorPassEmpty.setVisible(false);
        lbErrorPhoneEmpty.setVisible(false);
        lbErrorUserNameEmpty.setVisible(false);
        lbErrorNameInvalid.setVisible(false);
        //Set nut update an
        btUpdate.setVisible(false);
        lbUpdate.setVisible(false);
        btDelete.setVisible(false);
        lbDelete.setVisible(false);
        btChangePassWord.setVisible(false);
        this.setSize(400,605);
   this.getContentPane().setBackground(new Color(209, 209, 224));
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBackground = new javax.swing.JPanel();
        panelRegister = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        btChangePassWord = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordAgain = new javax.swing.JPasswordField();
        cbPosittion = new javax.swing.JComboBox<>();
        lbUpdate = new javax.swing.JLabel();
        lbRegister = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        cbDate = new datechooser.beans.DateChooserCombo();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btUpdate = new javax.swing.JButton();
        lbDelete = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        txtMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        lbErrorNameInvalid = new javax.swing.JLabel();
        lbErrorNameEmpty = new javax.swing.JLabel();
        lbErrorUserName = new javax.swing.JLabel();
        lbErrorUserNameEmpty = new javax.swing.JLabel();
        lbErrorPassEmpty = new javax.swing.JLabel();
        lbErrorPass = new javax.swing.JLabel();
        lbErrorPhone = new javax.swing.JLabel();
        lbErrorPhoneEmpty = new javax.swing.JLabel();
        lbErrorAddressEmpty = new javax.swing.JLabel();
        lbErrorMail = new javax.swing.JLabel();
        lbErrorMailEmpty = new javax.swing.JLabel();
        lbErrorUserNameExisting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setOpacity(0.95F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegister.setBackground(new java.awt.Color(51, 51, 51));
        panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Sign Up", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(255, 255, 102))); // NOI18N
        panelRegister.setPreferredSize(new java.awt.Dimension(250, 530));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtName.setCaretColor(new java.awt.Color(204, 0, 0));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.setDisabledTextColor(new java.awt.Color(69, 73, 74));
        txtName.setDragEnabled(true);
        txtName.setSelectedTextColor(new java.awt.Color(69, 73, 74));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        panelRegister.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 50));

        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(133, 173, 173));
        txtAddress.setText("ADDRESS*");
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        panelRegister.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 360, 50));

        radioNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioNam);
        radioNam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioNam.setForeground(new java.awt.Color(255, 255, 255));
        radioNam.setText("Male");
        radioNam.setContentAreaFilled(false);
        panelRegister.add(radioNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 40));

        radioNu.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(radioNu);
        radioNu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioNu.setForeground(new java.awt.Color(255, 255, 255));
        radioNu.setText("Female");
        radioNu.setContentAreaFilled(false);
        radioNu.setFocusPainted(false);
        panelRegister.add(radioNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, 40));

        btChangePassWord.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btChangePassWord.setText("CHANGE PASSWORD");
        btChangePassWord.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        panelRegister.add(btChangePassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 30));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(133, 173, 173));
        txtUsername.setText("USERNAME*");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        panelRegister.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, 50));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(133, 173, 173));
        txtPassword.setText("PASSWORD123456789");
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        panelRegister.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, 50));

        txtPasswordAgain.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordAgain.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
        txtPasswordAgain.setForeground(new java.awt.Color(133, 173, 173));
        txtPasswordAgain.setText("PASSWORD1234567890");
        txtPasswordAgain.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPasswordAgain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordAgainFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordAgainFocusLost(evt);
            }
        });
        txtPasswordAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordAgainActionPerformed(evt);
            }
        });
        panelRegister.add(txtPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 50));

        cbPosittion.setBackground(new java.awt.Color(255, 255, 255));
        cbPosittion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbPosittion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lí", "Quản kho", "Thu ngân" }));
        cbPosittion.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        panelRegister.add(cbPosittion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 110, 50));

        lbUpdate.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbUpdate.setForeground(new java.awt.Color(255, 255, 102));
        lbUpdate.setText("UPDATE");
        panelRegister.add(lbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 120, 30));

        lbRegister.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbRegister.setForeground(new java.awt.Color(255, 255, 102));
        lbRegister.setText("REGISTER");
        panelRegister.add(lbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 140, 30));

        btRegister.setBackground(new java.awt.Color(102, 102, 102));
        btRegister.setForeground(new java.awt.Color(255, 255, 0));
        btRegister.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btRegister.setBorder(null);
        btRegister.setBorderPainted(false);
        btRegister.setContentAreaFilled(false);
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        panelRegister.add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 180, 70));

        cbDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    cbDate.setCalendarBackground(new java.awt.Color(255, 255, 255));
    cbDate.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
    try {
        cbDate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(1999, 4, 1),
            new java.util.GregorianCalendar(1999, 4, 1))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    cbDate.setFieldFont(new java.awt.Font("SVNtimes new roman", java.awt.Font.BOLD, 14));
    try {
        cbDate.setForbiddenPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    cbDate.setLocale(new java.util.Locale("vi", "", ""));
    cbDate.setNavigateFont(new java.awt.Font("SVNtimes new roman", java.awt.Font.PLAIN, 12));
    panelRegister.add(cbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 50));

    txtSDT.setBackground(new java.awt.Color(255, 255, 255));
    txtSDT.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
    txtSDT.setForeground(new java.awt.Color(133, 173, 173));
    txtSDT.setText("PHONE NUMBER*");
    txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
    txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtSDTFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtSDTFocusLost(evt);
        }
    });
    panelRegister.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 170, 50));

    txtEmail.setBackground(new java.awt.Color(255, 255, 255));
    txtEmail.setFont(new java.awt.Font("Dubai Light", 2, 16)); // NOI18N
    txtEmail.setForeground(new java.awt.Color(133, 173, 173));
    txtEmail.setText("EMAIL*");
    txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
    txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtEmailFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtEmailFocusLost(evt);
        }
    });
    panelRegister.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 50));

    btUpdate.setBackground(new java.awt.Color(102, 102, 102));
    btUpdate.setForeground(new java.awt.Color(255, 255, 0));
    btUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
    btUpdate.setBorder(null);
    btUpdate.setBorderPainted(false);
    btUpdate.setContentAreaFilled(false);
    panelRegister.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 180, 70));

    lbDelete.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    lbDelete.setForeground(new java.awt.Color(255, 255, 102));
    lbDelete.setText("DELETE");
    panelRegister.add(lbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 120, 30));

    btDelete.setBackground(new java.awt.Color(102, 102, 102));
    btDelete.setForeground(new java.awt.Color(255, 255, 0));
    btDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
    btDelete.setBorder(null);
    btDelete.setBorderPainted(false);
    btDelete.setContentAreaFilled(false);
    panelRegister.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 70));

    txtMinimize.setBackground(new java.awt.Color(51, 51, 51));
    txtMinimize.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
    txtMinimize.setForeground(new java.awt.Color(255, 255, 102));
    txtMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtMinimize.setText("-");
    txtMinimize.setOpaque(true);
    txtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            txtMinimizeMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            txtMinimizeMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            txtMinimizeMouseExited(evt);
        }
    });
    panelRegister.add(txtMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 20));

    txtExit.setBackground(new java.awt.Color(51, 51, 51));
    txtExit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    txtExit.setForeground(new java.awt.Color(255, 255, 102));
    txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtExit.setText("x");
    txtExit.setOpaque(true);
    txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            txtExitMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            txtExitMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            txtExitMouseExited(evt);
        }
    });
    panelRegister.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 20));

    panelBackground.add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 610));

    getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 610));

    lbErrorNameInvalid.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorNameInvalid.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorNameInvalid.setText("Below 40 character");
    lbErrorNameInvalid.setToolTipText("");
    getContentPane().add(lbErrorNameInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 200, -1));

    lbErrorNameEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorNameEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorNameEmpty.setText("Name's empty");
    lbErrorNameEmpty.setToolTipText("");
    getContentPane().add(lbErrorNameEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, -1));

    lbErrorUserName.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorUserName.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorUserName.setText("Username's invalid");
    getContentPane().add(lbErrorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 180, 40));

    lbErrorUserNameEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorUserNameEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorUserNameEmpty.setText("Username's empty");
    lbErrorUserNameEmpty.setToolTipText("");
    getContentPane().add(lbErrorUserNameEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 170, -1));

    lbErrorPassEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorPassEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorPassEmpty.setText("Pass's empty");
    lbErrorPassEmpty.setToolTipText("");
    getContentPane().add(lbErrorPassEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 160, 20));

    lbErrorPass.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
    lbErrorPass.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorPass.setText("Pass don't match");
    getContentPane().add(lbErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, 20));

    lbErrorPhone.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorPhone.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorPhone.setText("Phone's invalid");
    getContentPane().add(lbErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 180, 50));

    lbErrorPhoneEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorPhoneEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorPhoneEmpty.setText("Phone's empty");
    lbErrorPhoneEmpty.setToolTipText("");
    getContentPane().add(lbErrorPhoneEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 150, -1));

    lbErrorAddressEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorAddressEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorAddressEmpty.setText("Address's empty");
    lbErrorAddressEmpty.setToolTipText("");
    getContentPane().add(lbErrorAddressEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 150, -1));

    lbErrorMail.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorMail.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorMail.setText("Email's invalid");
    getContentPane().add(lbErrorMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 180, 50));

    lbErrorMailEmpty.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorMailEmpty.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorMailEmpty.setText("Email's empty");
    lbErrorMailEmpty.setToolTipText("");
    getContentPane().add(lbErrorMailEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 150, -1));

    lbErrorUserNameExisting.setFont(new java.awt.Font("DialogInput", 3, 16)); // NOI18N
    lbErrorUserNameExisting.setForeground(new java.awt.Color(255, 51, 51));
    lbErrorUserNameExisting.setText("Username's existing");
    getContentPane().add(lbErrorUserNameExisting, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 220, 40));

    pack();
    }// </editor-fold>//GEN-END:initComponents
                 
    private void txtPasswordAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordAgainActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
               if(txtName.getText().trim().toUpperCase().equals(""))
               {
           txtName.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtName.setForeground(new Color(133,173,173));
           txtName.setBackground(Color.white);
           txtName.setText("NAME*");   
               }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
                if(txtName.getText().trim().toUpperCase().equals("NAME*"))
                {
           txtName.setFont(new Font("Dialog", Font.BOLD, 16));
           txtName.setForeground(new Color(10, 15, 15));
           txtName.setBackground(Color.white);
           txtName.setText("");
                }
           //do nothing
    }//GEN-LAST:event_txtNameFocusGained

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
                        if(txtUsername.getText().trim().toUpperCase().equals("USERNAME*"))
                        {
               txtUsername.setFont(new Font("Dialog", Font.BOLD, 16));
           txtUsername.setForeground(new Color(10, 15, 15));
           txtUsername.setText("");
                        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
                if(txtUsername.getText().trim().toUpperCase().equals(""))
               {
           txtUsername.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtUsername.setForeground(new Color(133,173,173));
           txtUsername.setText("USERNAME*");   
               }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
 
                        if(txtPassword.getText().trim().toUpperCase().equals("PASSWORD123456789"))
                        {
               txtPassword.setFont(new Font("Dialog", Font.BOLD, 16));
           txtPassword.setForeground(new Color(10, 15, 15));
           txtPassword.setText("");
                        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
                        if(txtPassword.getText().trim().toUpperCase().equals(""))
               {
           txtPassword.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtPassword.setForeground(new Color(133,173,173));
           txtPassword.setText("PASSWORD123456789"); 
               }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordAgainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordAgainFocusLost
        // TODO add your handling code here:
                  if(txtPasswordAgain.getText().trim().toUpperCase().equals(""))
               {
           txtPasswordAgain.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtPasswordAgain.setForeground(new Color(133,173,173));
           txtPasswordAgain.setText("PASSWORD1234567890"); 
               }
    }//GEN-LAST:event_txtPasswordAgainFocusLost

    private void txtPasswordAgainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordAgainFocusGained
        // TODO add your handling code here:
           if(txtPasswordAgain.getText().trim().toUpperCase().equals("PASSWORD1234567890"))
           {
           txtPasswordAgain.setFont(new Font("Dialog", Font.BOLD, 16));
           txtPasswordAgain.setForeground(new Color(10, 15, 15));
           txtPasswordAgain.setText("");
           }
    }//GEN-LAST:event_txtPasswordAgainFocusGained

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
          if(txtSDT.getText().trim().toUpperCase().equals("PHONE NUMBER*"))
          {
           txtSDT.setFont(new Font("Dialog", Font.BOLD, 16));
           txtSDT.setForeground(new Color(10, 15, 15));
           txtSDT.setText("");
          }
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        // TODO add your handling code here:
                          if(txtSDT.getText().trim().toUpperCase().equals(""))
               {
           txtSDT.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtSDT.setForeground(new Color(133,173,173));
           txtSDT.setText("PHONE NUMBER*"); 
               }
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
                  if(txtAddress.getText().trim().toUpperCase().equals("ADDRESS*"))
                  {
           txtAddress.setFont(new Font("Dialog", Font.BOLD, 16));
           txtAddress.setForeground(new Color(10, 15, 15));
           txtAddress.setText("");
                  }
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
             if(txtAddress.getText().trim().toUpperCase().equals(""))
               {
           txtAddress.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtAddress.setForeground(new Color(133,173,173));
           txtAddress.setText("ADDRESS*"); 
               }
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
                          if(txtEmail.getText().trim().toUpperCase().equals("EMAIL*"))
                  {
           txtEmail.setFont(new Font("Dialog", Font.BOLD, 16));
           txtEmail.setForeground(new Color(10, 15, 15));
           txtEmail.setText("");
                  }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
                    if(txtEmail.getText().trim().toUpperCase().equals(""))
               {
           txtEmail.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtEmail.setForeground(new Color(133,173,173));
           txtEmail.setText("EMAIL*"); 
               }
        
    }//GEN-LAST:event_txtEmailFocusLost

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btRegisterActionPerformed

    private void txtMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseExited
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtMinimizeMouseExited

    private void txtMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseEntered
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(200, 0,0));
    }//GEN-LAST:event_txtMinimizeMouseEntered

    private void txtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_txtMinimizeMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(new Color(200, 0,0));
        
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtExitMouseExited

    /**
     * @param args the command line arguments
     */
//    private void createAccount(String userName,String password)
//    {
//        try {
//            Connection connect=Connect();
//            String sql1=" insert into Account values (?,?)";
//            PreparedStatement pr1=connect.prepareStatement(sql1);
//            pr1.setString(1, userName);
//            pr1.setString(2, password);
//            pr1.executeUpdate();
//            pr1.close();
//            connect.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//   
// private void createStaff(String name,String userName,String sex,String position,String phoneNumber,String date,String address,String email)
// {
//        try {
//            Connection connect=Connect();
//            String sql=" insert into NhanVien (TENNV,USERNAME,GIOITINH,CHUCVU,SDT,NGAYSINH,DIACHI,EMAIL) values (?,?,?,?,?,?,?,?)";
//            PreparedStatement pr=connect.prepareStatement(sql);
//            pr.setString(1, name);
//            pr.setString(2, userName);
//            pr.setString(3, sex);
//            pr.setString(4, position);
//            pr.setString(5, phoneNumber);
//            pr.setString(6, date);
//            pr.setString(7, address);
//            pr.setString(8, email);
//            pr.executeUpdate();
//            pr.close();
//            connect.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(RegisterMember.class.getName()).log(Level.SEVERE, null, ex);
//        }
// }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btChangePassWord;
    public javax.swing.JButton btDelete;
    public javax.swing.JButton btRegister;
    public javax.swing.JButton btUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    public datechooser.beans.DateChooserCombo cbDate;
    public javax.swing.JComboBox<String> cbPosittion;
    public javax.swing.JLabel lbDelete;
    public javax.swing.JLabel lbErrorAddressEmpty;
    public javax.swing.JLabel lbErrorMail;
    public javax.swing.JLabel lbErrorMailEmpty;
    public javax.swing.JLabel lbErrorNameEmpty;
    public javax.swing.JLabel lbErrorNameInvalid;
    public javax.swing.JLabel lbErrorPass;
    public javax.swing.JLabel lbErrorPassEmpty;
    public javax.swing.JLabel lbErrorPhone;
    public javax.swing.JLabel lbErrorPhoneEmpty;
    public javax.swing.JLabel lbErrorUserName;
    public javax.swing.JLabel lbErrorUserNameEmpty;
    public javax.swing.JLabel lbErrorUserNameExisting;
    public javax.swing.JLabel lbRegister;
    public javax.swing.JLabel lbUpdate;
    private javax.swing.JPanel panelBackground;
    public javax.swing.JPanel panelRegister;
    public javax.swing.JRadioButton radioNam;
    public javax.swing.JRadioButton radioNu;
    public javax.swing.JTextField txtAddress;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtMinimize;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JPasswordField txtPasswordAgain;
    public javax.swing.JTextField txtSDT;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
